version: "3"
services: 
  mongo:
    image: 'mongo:latest'
    restart: always
  redis:
    image: 'redis:latest'
    restart: always
  nginx: 
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_ADD=mongo
      - MONGODB_PORT=27017
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./worker:/app
   